version: "3.9"

services:
  nginx:
    build: .
    image: heartexlabs/label-studio:latest
    ports:
      #- "8080:8085"
      - "443:8086"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=a3w6k4.myvserver.online
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=admin@plus.com
      - LABEL_STUDIO_PASSWORD=FMaIQ1cIFeW44II8q
      - NGINX_SSL_CERT=/certs/fullchain1.pem
      - NGINX_SSL_CERT_KEY=/certs/privkey1.pem
    volumes:
      - /home/unisbg:/label-studio/data:rw
      - /etc/letsencrypt/archive/a3w6k4.myvserver.online:/certs:ro
    command: nginx

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    expose:
      - "8000"
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=admin@plus.com
      - LABEL_STUDIO_PASSWORD=FMaIQ1cIFeW44II8q
      #- DJANGO_DB=default
      #- POSTGRE_NAME=postgres
      #- POSTGRE_USER=postgres
      #- POSTGRE_PASSWORD=
      #- POSTGRE_PORT=5432
      #- POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=a3w6k4.myvserver.online
      - JSON_LOG=1
#      - LOG_LEVEL=DEBUG
    volumes:
      - /home/unisbg:/label-studio/data:rw
    command: label-studio-uwsgi
volumes:
  static: {}